server:
  port: 8080

spring:
  datasource:
    url: jdbc:shardingsphere:classpath:sharding-config.yml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.app.miniapp.shardingdemo.entity

