server:
  #私有云部署不需要配置该端口
  port: 8080
  max-http-header-size: 1024000
  servlet:
    multipart:
      max-file-size: 50000000
      max-request-size: 200000000
    context-path: /app

spring:
  datasource:
    url: jdbc:shardingsphere:classpath:sharding-config.yml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.app.miniapp.shardingdemo.entity

logging:
  level:
    com.app.miniapp.shardingdemo.mapper: debug

pcc:
